package com.oktayosman.ticketcenter.support;

import com.oktayosman.ticketcenter.model.Distributor;
import com.oktayosman.ticketcenter.model.Event;
import com.oktayosman.ticketcenter.model.Notification;
import com.oktayosman.ticketcenter.model.Organizer;
import com.oktayosman.ticketcenter.model.Role;
import com.oktayosman.ticketcenter.model.SeatCategory;
import com.oktayosman.ticketcenter.model.SeatType;
import com.oktayosman.ticketcenter.model.TicketSaleItem;
import com.oktayosman.ticketcenter.model.User;

import java.lang.reflect.Field;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;

/**
 * Small builders for unit tests. Entity ids are generated by the database and have
 * no setters, so they are set reflectively here.
 */
public final class TestData {

    private TestData() {}

    public static void setId(Object target, String fieldName, Long id) {
        try {
            Field field = target.getClass().getDeclaredField(fieldName);
            field.setAccessible(true);
            field.set(target, id);
        } catch (ReflectiveOperationException e) {
            throw new IllegalStateException("Cannot set " + fieldName + " on " + target.getClass(), e);
        }
    }

    public static Event event(Long id, String name, int capacity, int ticketLimit) {
        Event event = new Event(name, "Venue", LocalDateTime.now().plusDays(30), ticketLimit, null);
        event.setCapacity(capacity);
        event.setSeatTypes(new ArrayList<>());
        setId(event, "id", id);
        return event;
    }

    public static SeatType seatType(Long id, Event event, SeatCategory category,
                                    String price, Integer totalSeats, int soldSeats) {
        SeatType seatType = new SeatType();
        setId(seatType, "id", id);
        seatType.setEvent(event);
        seatType.setSeatCategory(category);
        seatType.setPrice(new BigDecimal(price));
        seatType.setTotalSeats(totalSeats);
        seatType.setSoldSeats(soldSeats);
        return seatType;
    }

    /** An item as the sale form would send it: only the seat type id and quantity are meaningful. */
    public static TicketSaleItem formItem(Long seatTypeId, Integer quantity) {
        SeatType stub = new SeatType();
        setId(stub, "id", seatTypeId);
        TicketSaleItem item = new TicketSaleItem();
        item.setSeatType(stub);
        item.setQuantity(quantity);
        return item;
    }

    public static User user(Long id, String username, String roleName) {
        User user = new User("First", "Last", username + "@example.com", username, "password123",
                roleName != null ? new Role(roleName) : null);
        setId(user, "id", id);
        return user;
    }

    public static Organizer organizer(Long userId) {
        Organizer organizer = new Organizer(user(userId, "org" + userId, "ORGANIZER"), "Org", 5.0);
        organizer.setUserId(userId);
        return organizer;
    }

    public static Distributor distributor(Long id, String username) {
        Distributor distributor = new Distributor(user(id != null ? id + 100 : null, username, "DISTRIBUTOR"), 0.1);
        setId(distributor, "id", id);
        return distributor;
    }

    public static Notification notification(Long id, User recipient) {
        Notification notification = new Notification("msg", recipient);
        setId(notification, "id", id);
        return notification;
    }
}
